### PR TITLE
Add menu option to sort lines in a note

### PR DESCRIPTION
**Pull request by jojhelfer**
This adds a menu option to sort all the lines in a note.
This is a feature I have personally been wanting for a long time.

### CODE REVIEW

**Review by cbkerr — COMMENTED** [review]
Seems useful for keeping a simple list. A few things to consider:

I think the user may expect this to sort without consideration for org markup characters.
image


I think this might be better suited to add to the menu that appears on text selection so user can control which parts to sort. 
* sort different bulleted lists separately
* ignore bolded headings if used to section the note

image

**Comment by bemyak** [comment]
About markup characters, I'm not so sure. Imagine you have a list like this:
```
- *item 21 is urgent*
- item 22 is normal
- *item 23 is urgent again*
```

It _could_ make sense to move all bold items together to the top of the list. We can assume that users are familiar with the ORG format and they would understand what is going on.

About where the sort option would be located, I disagree with @cbkerr here. If I would want to select lines, I wouldn't _select_ them. Selecting works **horizontally** (from left to write in most languages), while sorting is **vertical** (you rearrange lines). Sorting doesn't care about the caret position on the line, so from the UX perspective, it's a bit silly to require a user to set it.

So, I would prefer to keep the things simple and not overcomplicate it unless requested and well justified.

**Review by bemyak — APPROVED** [review]
See comment above

**Review by amberin — APPROVED** [review]
I suggest merging this, and we can always change/improve it upon feedback. My guess is it will be a pretty niche feature, but not get in anyone's way.

**Review by cbkerr — APPROVED** [review]
> If I would want to sort lines, I wouldn't select them.

I agree that putting this option behind selection is not discoverable enough.

While I still think sorting while ignoring formatting characters could be a useful feature, we can always add it later if it's needed.

Thanks for the contribution!

**Comment by jojhelfer** [comment]
You're welcome, and thanks for approving it!
Thanks also to all for the discussion about possible improvements.
Another such improvement could be to turn "Sort note" into a submenu with certain more refined options, which could be buttons or maybe checkboxes (e.g., sort in reverse, or ignore markup characters, as was being discussed).

**Pull request merged**
