### PR TITLE
Support subfolders for Sync locations

### LINKED ISSUE #175: Support subfolders for Sync locations
When I set up some directory as a sync location, only org files that are located directly in that directory are read. Org files in subfolders are not considered at all. This makes it unnecessary cumbersome to handle use case with org files inside a folder hierarchy. Also, linking between those org files / notebooks doesn't work, since Orgzly knows nothing about subfolders.

It would be good if Orgzly supported subfolders inside an sync location.

There is a similar ticket reported at #146 which is Git related. This one is more general.

### PR DESCRIPTION
**Pull request by amberin**
This resolves #175, which was originally https://github.com/orgzly/orgzly-android/issues/225 (the most "liked" issue). See especially this comment for background: https://github.com/orgzly-revived/orgzly-android-revived/issues/175#issuecomment-2128058037

### CODE REVIEW

**Comment by amberin** [comment]
Would especially love to get some feedback from @NatKarmios on the change to ExternalAccessReceiver. I don't use that myself, so I don't know how to test it.

**Review by alensiljak — APPROVED** [review]

**Comment by credmp** [comment]
Great work! If there is some way to contribute to testing this feature, please let me know, will happily do some bughunting on the functionality.

**Comment by amberin** [comment]
> Great work! If there is some way to contribute to testing this feature, please let me know, will happily do some bughunting on the functionality.

Yes, if you could try out the [latest beta build](https://github.com/orgzly-revived/orgzly-android-revived/releases/tag/v1.8.27-beta.2), that would be highly valuable!

**Comment by credmp** [comment]
I installed the beta (v1.8.27-beta.2), created a webdav share with subfolders and top level files. All files are synced correctly and the overview shows from which subfolder they come, this is great. 

I performed various editing operations, both client and server side, introduced conflicts etc. The functionality holds well, no issues found so far. Interestingly if I refresh a note from within the note (open note, pull down) it will retrieve the server version, but it will not update the server version. Update only happens in the notes list view.

New files go to the top level directory.

Things that might be improved:

- Allow sorting on the directory name first before the note names, now it is sorted on the title
- In the left slide out pane, show a tree of the directory structure, allow folding
- In the overview, allow folding on directory level

I think the above should be actual tickets for future work, but perhaps you already have some sort of roadmap, if not I will happily create the tickets.

Great work!

**Comment by amberin** [comment]
@credmp Thank you for testing!

> Interestingly if I refresh a note from within the note (open note, pull down) it will retrieve the server version, but it will not update the server version. Update only happens in the notes list view.

Could you please double check and help me reproduce, because this sounds very curious. There is only one sync workflow, no matter where you trigger it from (which bothers me, since I'd love to be able to sync a single notebook).

> - Allow sorting on the directory name first before the note names, now it is sorted on the title
> - In the left slide out pane, show a tree of the directory structure, allow folding
> - In the overview, allow folding on directory level

Yes, this seems to be what @nevenz had in mind when discussing subfolders in previous issues. I'm afraid it's out of my reach, since it would require quite some database and UI changes. I saw this as low-hanging fruit to achieve some rudimentary support, although it's quite an ugly hack. The only thing Orgzly is now aware of is that notebook names or file paths may contain a "/", but there is no other contract between repos and the rest of the app. So endowing the app with a proper "directory" concept is quite some more work. (This is why you can't e.g. sort on directory, because there is only a notebook name with a slash in it.)

It would be great if you'd file tickets about these things.

Thanks again for testing and reporting any findings.

**Comment by amberin** [comment]
> Ofc using external content providers isn't exactly officially supported, but just putting it out here

@sethidden Interesting! Did this webdav mount work for you before this version?

There could be some assumptions about what content:// URLs usually look like which are causing trouble. It's very bad practice to draw conclusions from those URLs, as every ContentProvider works differently, but it seemed like a working primitive solution to cram regular directories into our SyncRepo interface.

If this type of setup worked for you before, this is pf course very unwelcome and must be reconsidered.

**Comment by credmp** [comment]
> > Interestingly if I refresh a note from within the note (open note, pull down) it will retrieve the server version, but it will not update the server version. Update only happens in the notes list view.
> 
> Could you please double check and help me reproduce, because this sounds very curious. There is only one sync workflow, no matter where you trigger it from (which bothers me, since I'd love to be able to sync a single notebook).

Double checked, it seems to rather be an issue with my WebDav host, the sync occured but during my testing the webdav host did not trigger sync to my desktop host. On the server it was updated.
 
So, false alarm, it works correctly!

**Comment by amberin** [comment]
> Some further attempts to access the mysterious content:// uri over adb (without Orgzly Revived in the picture):

@sethidden Thanks. Yes, this makes sense, because only an app which has requested permission via the file picker is allowed to access that URL. Which of course is really frustrating when trying to debug and test these things.

**Comment by amberin** [comment]
Let's continue exploring this in #304.

**Pull request merged**
