### PR TITLE
adding the fdroid build, v1

### PR DESCRIPTION
**Pull request by alensiljak**
Initial version of the f-droid build. Please double-check and/or let's try it out. 

I'm not sure if we will need to create a new version to test this. Perhaps we can regenerate the same version that is already published.
This only creates another .apk binary, for the fdroid blavor. Which is what F-Droid will use.

### CODE REVIEW

**Comment by alensiljak** [comment]
I have doubts about the last step, creating a release draft. The intention is to have both binaries attached to the same version, in any case.
Can't know for sure what happens until we try to run this.

**Review by amberin — APPROVED** [review]
LGTM, let's try it out. The current version is a beta though, and there is a separate workflow for those.

I suggest we release 1.8.12 and try this. We know it has bugs, but I believe they were all in 1.8.11.

**Comment by alensiljak** [comment]
ok, I've adjusted the last step to try to attach the binary to a release. No idea which release that would be. 🙈

Where is the release being published from? Main or another branch?

**Comment by alensiljak** [comment]
Right. I'll make the same adjustment for the prerelease...

**Comment by alensiljak** [comment]
Done. We can experiment with the pre-release, then.

**Comment by alensiljak** [comment]
Oops, wait. That is an old plugin.
Checking https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets

**Review by amberin — APPROVED** [review]

**Pull request merged**
